version: "3.7"

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: "/data/postgres"
    volumes:
      - db_data/:/var/lib/postgresql/data/postgres
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    networks: ["todo-grpc"]

networks:
  todo-grpc:
    name: todo-

volumes:
  db_data:
    driver: local
